---
- name: Reload sysctl.conf
  command: /sbin/sysctl -p
  become: true

# Master
- name: Start Spark Master
  systemd:
    name: spark-master
    state: started
    enabled: yes
    daemon_reload: yes

- name: Stop Spark Master
  systemd:
    name: spark-master
    state: stopped
    enabled: no

- name: Restart Spark Master
  systemd:
    name: spark-master
    state: restarted
    enabled: yes
    daemon_reload: yes

# Worker
- name: Start Spark Worker
  systemd:
    name: spark-slave
    state: started
    enabled: yes
    daemon_reload: yes

- name: Stop Spark Worker
  systemd:
    name: spark-slave
    state: stopped
    enabled: no

- name: Restart Spark Worker
  systemd:
    name: spark-slave
    state: restarted
    enabled: yes
    daemon_reload: yes