---
# Worker
- name: Start Spark Worker
  systemd:
    name: spark-slave
    state: started
    enabled: yes
    daemon_reload: yes

- name: Stop Spark Worker
  systemd:
    name: spark-slave
    state: stopped
    enabled: no

- name: Restart Spark Worker
  systemd:
    name: spark-slave
    state: restarted
    enabled: yes
    daemon_reload: yes
