---
# This playbook contains common plays that will be run on all nodes.

- name: Install commonly used packages via yum
  yum:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - vim
    - screen
    - tmux
    - git-core
    - ntp
    - iptraf
    - sysstat
    - xfsprogs

- name: Set locales
  sudo: yes
  command: localectl set-locale LANG=en_US.UTF-8

- name: Set timezone to UTC
  timezone:
    name: UTC

# Modify motd
- name: Add dynmotd
  lineinfile:
    line: '/usr/local/bin/dynmotd'
    dest: /etc/profile
    state: present
    create: true

- name: Copy datavisor motd
  template:
    src: dvlogo.j2
    dest: /usr/local/bin/dynmotd
    owner: root
    group: root
    mode: 0755

- name: install awscli
  pip:
    name: awscli

- name: Create datavisor directory
  file:
    path: /opt/datavisor/scripts
    state: directory
    mode: 0755

- name: Copy Scripts
  template:
    src: add_tags.sh.j2
    dest: /opt/datavisor/scripts/add_tags.sh
    mode: 0755